#! /bin/bash
hostname=$(hostname)

if [ -z "$CLUSTER_WITH" -o "$CLUSTER_WITH" = "$hostname" ]; then
  rabbitmq-server
#  while [ ! -f "/var/log/rabbitmq/log/crash.log" ]; do
#    echo "waiting"
#    sleep 2s
#  done
#  echo "running"
#  rabbitmqctl start_app
#  if [ "$RABBITMQ_DEFAULT_USER" ]; then
#      if [ ! "$RABBITMQ_DEFAULT_PASS" ]; then
#        RABBITMQ_DEFAULT_PASS=public
#      fi
#      rabbitmqctl add_user "$RABBITMQ_DEFAULT_USER" "$RABBITMQ_DEFAULT_PASS"
#      rabbitmqctl set_user_tags "$RABBITMQ_DEFAULT_USER" administrator
#      rabbitmqctl set_permissions "$RABBITMQ_DEFAULT_USER" / '.*' '.*' '.*'
#  fi
else
  echo "Running as clustered server"
  rabbitmq-server -detached
  while [ ! -f "/var/log/rabbitmq/log/crash.log" ]; do
    echo "waiting"
    sleep 2s
  done
  echo "running"
  rabbitmqctl stop_app
  echo $RABBITMQ_NODENAME@$CLUSTER_WITH
#
  echo "Joining cluster $CLUSTER_WITH"
  rabbitmqctl join_cluster ${ENABLE_RAM:+--ram} $RABBITMQ_NODENAME@$CLUSTER_WITH
#
  rabbitmqctl start_app
  tail -f /var/log/rabbitmq/log/*
fi
